replaced tabs with spaces my script replaced all tabs with four spaces. It says that it succeeded for all files except 1. BPS/BSP/STM32F413/STM32F4xx_StdPeriph_Driver/Src/stm32f4xx_qspi.c 2. BPS/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c 3. BPS/RTOS/uCOS-III-STM32F4/uCOS-III/Ports/ARM-Cortex-M4/Generic/IAR/os_cpu_c.c
I think the failures were caused by non-unicode characters in these files, which broke Python's file.read() method. The error thrown was:

UnicodeDecodeError: 'utf8' codec can't decode byte <something I forgot to write down> in position <something I forgot to write down>: invalid start byte

I didn't feel like fixing this error because we will probably not edit these files